apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
      - name: app-container
        image: mostafamedhat1/todo-app
        resources:
          requests:
            cpu: 300m       
            memory: 256Mi   
          limits:
            cpu: 400m       
            memory: 512Mi   
        env:
         - name: DB_HOST
           value: "mysql"
         - name: DB_USER
           value: "root"
         - name: DB_PASS
           value: "password"
         - name: DB_DATABASE
           value: "todo_db" 
        ports:
        - containerPort: 5000
