apiVersion: batch/v1
kind: Job
metadata:
  name: create-tasks-table-job
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:8.0
        envFrom:
        - secretRef:
            name: db-credentials
        command: ["sh", "-c"]
        args:
          - |
            mysql -h $DB_HOST -u $DB_USER -p$DB_PASS $DB_DATABASE -e "CREATE TABLE IF NOT EXISTS tasks ( id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT, is_complete BOOLEAN DEFAULT false );"
      restartPolicy: Never
